In [3]:
import numpy as np

In [4]:
x=np.array([[3,5,7],[2,3,4,],[3,4,5]])

In [5]:
x

array([[3, 5, 7],
       [2, 3, 4],
       [3, 4, 5]])

In [12]:
x.shape

(3, 3)

In [15]:
n=x.shape
n

(3, 3)

In [20]:
m,n=x.shape
n

3

In [21]:
x[:,0:1]      #to get first column

array([[3],
       [2],
       [3]])

In [22]:
x[:,0:2]

array([[3, 5],
       [2, 3],
       [3, 4]])

In [23]:
x[:,2:3]

array([[7],
       [4],
       [5]])

In [24]:
a=1.3
np.exp(a)    #2.7


3.6692966676192444

In [25]:
a=np.array([])
a=np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
k=np.array([0,0,0])

In [27]:
x

array([[3, 5, 7],
       [2, 3, 4],
       [3, 4, 5]])

In [29]:
g=k.dot(x)     #matrix multiplaction
g

array([0, 0, 0])