# Arrays


In [1]:
import array as arr

In [2]:
a=arr.array('i',[1,4,3])    #creating an array 

In [3]:
a

array('i', [1, 4, 3])

In [4]:
b=arr.array('i',[4,3,1])

In [5]:
b

array('i', [4, 3, 1])

In [6]:
a.append(4)          #adding

In [7]:
a

array('i', [1, 4, 3, 4])

In [8]:
a[::-1]           #reversing

array('i', [4, 3, 4, 1])

In [9]:
a[1:]           #slicing

array('i', [4, 3, 4])

In [10]:
a.pop(1)             #removing

4

In [11]:
a

array('i', [1, 3, 4])

In [12]:
a.remove(1)
a

array('i', [3, 4])

In [13]:
for i in a:
    print(i,end=" ")

3 4 

In [17]:
a+b             #concatenation

array('i', [3, 4, 4, 3, 1])

# NUMPY

In [15]:
import numpy as np

In [16]:
k=np.array([(7,2,3),(2,5,6)])
p=np.array([(2,1,3),(1,4,8)])
k

array([[7, 2, 3],
       [2, 5, 6]])

In [17]:
p

array([[2, 1, 3],
       [1, 4, 8]])

In [18]:
k.ndim          #to check the dimensions

2

In [19]:
p.itemsize        #to check the size

4

In [20]:
k.dtype              #to know the datatype

dtype('int32')

In [21]:
k.size            #to know the size

6

In [22]:
p.shape            #to check the shape

(2, 3)

In [23]:
p.reshape(3,2)                  #reshape

array([[2, 1],
       [3, 1],
       [4, 8]])

In [24]:
p.min()               #to know the minimum value

1

In [25]:
p.max()               #to know the maximum number in the array

8

In [26]:
p.sum()              #to check the sum of the array

19

In [27]:
g=np.linspace(1,8,6)       #to check the numbers between the 1 and 4
g

array([1. , 2.4, 3.8, 5.2, 6.6, 8. ])

In [28]:
p.sum(axis=0)         #columnwise

array([ 3,  5, 11])

In [29]:
k.sum(axis=1)           #row wise

array([12, 13])

In [31]:
np.sqrt(p)         #squreroot

array([[1.41421356, 1.        , 1.73205081],
       [1.        , 2.        , 2.82842712]])

In [32]:
np.mean(k)          #mean

4.166666666666667

In [33]:
np.std(k)           #standard deviation

1.9507833184532708

In [34]:
p

array([[2, 1, 3],
       [1, 4, 8]])

In [36]:
p[0:3,1]

array([1, 4])

In [37]:
p[1,1]

4

In [38]:
k

array([[7, 2, 3],
       [2, 5, 6]])

In [39]:
k[k>2]                  #to know the greater number then 2,1

array([7, 3, 5, 6])

In [40]:
k[k>1]

array([7, 2, 3, 2, 5, 6])

In [41]:
k[k!=1]              #not equal numbers

array([7, 2, 3, 2, 5, 6])

In [42]:
k.sort()             #sorting
k

array([[2, 3, 7],
       [2, 5, 6]])

In [43]:
k+p               #arithmetic operators

array([[ 4,  4, 10],
       [ 3,  9, 14]])

In [44]:
k-p

array([[ 0,  2,  4],
       [ 1,  1, -2]])

In [45]:
k/p

array([[1.        , 3.        , 2.33333333],
       [2.        , 1.25      , 0.75      ]])